dashboard/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    dashboard,
    profile,
    profile_edit,
    messages,
    messages_api,
    projects,
    projects_api,
    LoginView,
    EducationView,
    )

app_name = 'dashboard'
urlpatterns = [

    path('', dashboard, name='dashboard'),

    path('profile/', profile, name='profile'),
    path('profile/edit/', profile_edit, name='profile_edit'),

    path('messages', messages, name='messages'),
    path('messages/api/', messages_api, name='messages_api'),

    path('projects', projects, name='projects'),
    path('projects/api/', projects_api, name='projects_api'),

    path('education/', EducationView.as_view(), name='education'),
    # path('education/', EducationView.as_view(), name='one_education'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    homePage,
    projectsPage,
    projectDetail,
    search,
    handler404,
)

from django.conf import settings
from django.conf.urls.static import static


handler404 = handler404

urlpatterns = [

    path('', homePage, name='homePage'),
    path('projects/', projectsPage, name='projectsPage'),
    path('projects/<str:slug>/', projectDetail, name='projectDetail'),
    path('search/', search, name='search'),

    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from info.models import Information, Project



class EditProfileForm(forms.ModelForm):
	
	class Meta:
		model = Information
		exclude = ('born_date', 'address', 'cv')

class CreateProjectForm(forms.ModelForm):

	class Meta:
		model = Project
		exclude = ('Slug',)

dashboard/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user

from rest_framework.views import APIView
from rest_framework import authentication, permissions
from rest_framework.response import Response
from rest_framework import status

from .forms import EditProfileForm, CreateProjectForm

from info.models import Information, Message, Project




class CsrfExemptSessionAuthentication(authentication.SessionAuthentication):
    def enforce_csrf(self, request):
        return

# we use this class to login and check the user if she/he logged in.
class LoginView(APIView):
    permission_classes = [permissions.AllowAny]
    authentication_classes = [CsrfExemptSessionAuthentication]
    def post(self, request):
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        
        if not username or not password:
            return render(request, "login.html", {'message': 'Please enter both username and password'})

        user = authenticate(
            username = username,
            password = password
            )
        if user:
            login_user(request, user)
            return redirect('dashboard:dashboard')
        return render(request, "login.html", {'message': 'Invalid Username or Password'})

    def get(self, request):
            return render(request, "login.html", {})


@login_required()
def dashboard(request):
    template_name = 'dashboard.html'
    profile = Information.objects.first()
    return render(request, template_name, {'profile':profile, 'dashboard': True})


@login_required()
def profile(request):
    template_name = 'profile.html'
    context = {}
    profile = Information.objects.first()
    context.update({'profile_active': True, 'profile': profile})
    return render(request, template_name, context)


@login_required()
def profile_edit(request):
    if request.method == 'POST':
        instance = Information.objects.first()

        avatar = request.FILES.get('avatar', False)
        if avatar:
            account = Information.objects.first()
            account.avatar = avatar
            account.save()
            return redirect('dashboard:profile')
        else:
            form = EditProfileForm(instance=instance, data=request.POST)
            if form.is_valid():
                form.save()
                return JsonResponse({'success': True})
            return JsonResponse({'success': False, 'errors': form.errors})
    return JsonResponse({'status':'bad request'})


@login_required()
def messages(request):
    template_name = 'messages.html'
    context = {}
    profile = Information.objects.first()
    messages = Message.objects.all().order_by('-send_time')

    page = request.GET.get('page', 1)

    paginator = Paginator(messages, 6)

    try:
        messages = paginator.page(page)
    except PageNotAnInteger:
        messages = paginator.page(1)
    except EmptyPage:
        messages = paginator.page(paginator.num_pages)

    context.update({'messages_active': True, 'messages': messages, 'profile': profile})
    return render(request, template_name, context)

@login_required()
def messages_api(request):
    if request.method == 'POST':
        type = request.POST.get('option_type')
        message_id = request.POST.get('message_id')
        if type == "delete":
            message = Message.objects.get(id=int(message_id))
            message.delete()
            return JsonResponse({'status': 'success'})
        elif type == "view":
            message = Message.objects.get(id=int(message_id))
            if not message.is_read:
                message.is_read = True
                message.save()
            return JsonResponse({'status': 'success'})
        elif type == "search":
            search_text = request.POST.get('search_text')

            lookups = Q(name__icontains=search_text) | Q(
                email__icontains=search_text) | Q(message__icontains=search_text)

            messages = Message.objects.filter(lookups).values()
            messages = list(messages)

            return JsonResponse({'status': 'success', 'messages': messages})
    return JsonResponse({'status': 'bad request'})


@login_required()
def projects(request):
    template_name = 'dashboard_projects.html'
    context = {}
    profile = Information.objects.first()
    projects = Project.objects.all().order_by('-id')
    context.update({'projects_active': True, 'projects': projects, 'profile': profile})
    return render(request, template_name, context)

@login_required()
def projects_api(request):
    if request.method == 'POST':

        if request.POST.get('type') == 'create':
            form = CreateProjectForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return JsonResponse({'status': 'Create Project Successfully', 'code': 200})
            else:
                return JsonResponse({'status': 'Create Project Failed', 'code': 400, 'errors':form.errors})

        elif request.POST.get('type') == 'update':
            id = int(request.POST.get('id'))
            if request.POST.get('first', False):
                project = Project.objects.filter(id=id).values()
                return JsonResponse({'project':list(project)[0], 'code': 200})
            else:
                project = Project.objects.get(id=id)
                form = CreateProjectForm(request.POST, request.FILES, instance=project)
                if form.is_valid():
                    form.save()
                    return JsonResponse({'status': 'Update Project Successfully', 'code': 200})
                else:
                    return JsonResponse({'status': 'Update Project Failed', 'code': 400, 'errors':form.errors})
            return JsonResponse({'status': 'Project Does Not Exist', 'code': 400})

        elif request.POST.get('type') == 'delete':
            id = int(request.POST.get('id'))
            Project.objects.filter(id=id).delete()
            return JsonResponse({'status': 'Remove Project Successfully', 'code': 200})

    return JsonResponse({'status': 'Bad Request'})



from info.models import Education
from .serializers import *

class EducationView(APIView):
    authentication_classes = [CsrfExemptSessionAuthentication]
    permission_classes = [permissions.IsAdminUser]

    def get(self, request):
        education = Education.objects.all()
        return render(request, 'dashboard_education.html', {'education':education})

    def post(self, request):
        serializer = EducationSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

dashboard/templates/dash_navbar.html
<!-- Topbar -->{% load static %}
    <nav class="navbar navbar-expand topbar mb-4 static-top shadow dash-navbar">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <div class="title">
            <h1 class="h4  text-gray-800">Alex Githui</h1>
        </div>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle message-icon" href="#" id="messagesDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <!-- Counter - Messages -->
                    <span class="badge badge-danger badge-counter">7</span>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="messagesDropdown">
                    <div class="massage-header py-3 text-center">Messages Counter</div>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="{% static 'img/message.svg' %}"
                                alt="">
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">Hi there! I am wondering if you can help me with a
                                problem I've been having.</div>
                            <div class="small text-gray-500">Emily Fowler</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="{% static 'img/message.svg' %}"
                                alt="">
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">Hi there! I am wondering if you can help me with a
                                problem I've been having.</div>
                            <div class="small text-gray-500">Emily Fowler</div>
                        </div>
                    </a>

                    <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">Alex Githui</span>
                    <img class="img-profile rounded-circle"
                        src="{% if user.avatar %}{{user.avatar.url}}{% else %}{% static 'img/default-avatar.svg' %}{% endif %}">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="userDropdown">
                    <a class="dropdown-item user-dropdown" href="#">
                        <i class="fas fa-user mr-2"></i>
                        Profile
                    </a>
                    <a class="dropdown-item user-dropdown" href="/">
                        <i class="fas fa-eye mr-2"></i>
                        <span>View Site</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item user-logout" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt mr-2"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

</nav>
    <!-- End of Topbar -->

dashboard/templates/dash_sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav sidebar dash_sidebar" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    
    <a class="sidebar-brand d-flex align-items-center justify-content-center">
        <div class="sidebar-brand-icon text-white">
            <i class="fas fa-tachometer-alt"></i>
        </div>
        <div class="sidebar-brand-text dash-icon">Dashboard</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Information
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item my-1">
        <a class="{% if profile_active %}link-active{% endif %}" href="{% url 'dashboard:profile' %}">
            <i class="fas fa-cog"></i>
            <span>Profile</span>
        </a>
    </li>
    <li class="nav-item mb-1">
        <a class="{% if messages_active %}link-active{% endif %}" href="{% url 'dashboard:messages' %}">
            <i class="fas fa-envelope"></i>
            <span>Messages</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider mt-2">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Charts -->
    <li class="nav-item mt-1">
        <a class="" href="charts.html">
            <i class="fas fa-chart-area"></i>
            <span>Projects</span></a>
    </li>
    <li class="nav-item mt-1">
        <a class="" href="charts.html">
            <i class="ni ni-atom"></i>
            <span>Competences</span></a>
    </li>

    <li class="nav-item mt-1">
        <a class="" href="charts.html">
            <i class="ni ni-hat-3"></i>
            <span>Educations</span></a>
    </li>

    <li class="nav-item my-1">
        <a class="" href="charts.html">
            <i class="ni ni-archive-2"></i>
            <span>Experiences</span></a>
    </li>
</ul>
<!-- End of Sidebar -->

dashboard/templates/dashboard.html
{% extends 'base.html' %}

{% load static %}
{% block style %}
    <link type="text/css" href="{% static 'dashboard.css' %}" rel="stylesheet">
{% endblock style %}

{% block body %}

<div class="container mt-lg-8">
    <div class="row">
        <div class="col-lg-4 sidebar p-0">
            <a href="{% url 'dashboard:dashboard' %}">
                <div class="row info {% if dashboard %}dashboard-active {% else %}info-unactive{% endif %}">
                    <div class="col-2 pic">
                        <div class="profile-pic shadow" style="background-image: url('{% if profile.avatar %}{{profile.avatar.url}}{% else %}{% static 'img/default-avatar.svg' %}{% endif %}')">
                        </div>
                    </div>
                    <div class="col-10 name">
                        <h5 class="full-name">{{profile.name_complete}}</h5>
                        <p class="email">{{profile.email}}</p>
                    </div>
                </div>
            <a/>
            <hr class="m-0 mb-1">
            <ul class="sidebar-list">
                <a href="{% url 'dashboard:profile' %}">
                    <li class="{% if profile_active %}link-active{% endif %}">
                        {% comment %} <img src="{% static 'img/profile.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-user dashboard-icon"></i>
                        Profile
                    </li>
                </a>
                <a href="{% url 'dashboard:messages' %}">
                    <li class="{% if messages_active %}link-active{% endif %}">
                        {% comment %} <img src="{% static 'img/messages.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-envelope-download dashboard-icon"></i>
                        Messages
                    </li>
                </a>
                <hr class="sidebar-line">
                <a href="{% url 'dashboard:education' %}">
                    <li>
                        {% comment %} <img src="{% static 'img/education.svg' %}" width='28px'> {% endcomment %}
                        <i class="uil uil-graduation-cap dashboard-icon"></i>
                        Educations
                    </li>
                </a>
                <a href="{% url 'dashboard:profile' %}">
                    <li>
                        {% comment %} <img src="{% static 'img/competences.svg' %}" width='28px'> {% endcomment %}
                        <i class="uil uil-award dashboard-icon"></i>
                        Competences
                    </li>
                </a>
                <a href="{% url 'dashboard:profile' %}">
                    <li>
                        {% comment %} <img src="{% static 'img/experiences.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-spinner-alt dashboard-icon"></i>
                        Experiences
                    </li>
                </a>
                <a href="{% url 'dashboard:projects' %}">
                    <li class="{% if projects_active %}link-active{% endif %}">
                        {% comment %} <img src="{% static 'img/dash-projects.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-folder-open dashboard-icon"></i>
                        Projects
                    </li>
                </a>
            </ul>
            <hr class="sidebar-line">
            <div class="container text-center sidebar-footer">
                <a href="{% url 'homePage' %}">
                    <img class="svg-icon-home" src="{% static 'img/home-icon.svg' %}" width='20px'>
                    Home
                </a>
                <a href="{% url 'dashboard:logout' %}" id="logout">
                    <img class="svg-icon-logout" src="{% static 'img/logout-icon.svg' %}" width='20px'>
                    Logout
                </a>
            </div>
        </div>
        <div class="col-lg-8 dashboard-content pl-lg-4">
            {% block dashboardContent %}
                <div class="dashboard-title">Dashboard</div>
                <div class=""><small>Welcome Again</small></div>
                <div class="row">
                    <div class="col-12 card">
                        <div class="">
                            <div class="">
                                <div class="">
                                    Welcome Again
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            {% endblock dashboardContent %}
        </div>
    </div>
</div>

<div class="container dash-footer my-6 py-2">
    <div class="text-center">
        <p>Copyright © {% now "Y" %} Hitz Committed. All rights reserved</p>
        <p class="coder">Built with <i class="fa fa-heart text-danger"></i> in Django By <a href="https://github.com/HitzCommitted">Hitz Committed</a></p>
    </div>
</div>


{% endblock body %}



{% block script %}
    <script src="{% static 'dashboard.js' %}"></script>
{% endblock script %}

dashboard/templates/login.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}Login{% endblock title %}
{% comment %} {% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %} {% endcomment %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center mt-6 mb-8">
			<div class="col-lg-6 col-12 text-center">
				<div class="login-card">
					<div class="login-card-header">
						<h3>Welcome</h3>
					</div>
					<div class="mx-5">
						<div id="content-main">

						{% if user.is_authenticated %}
							<meta http-equiv="REFRESH" content="0;url={{ request.scheme }}://{{ request.META.HTTP_HOST }}/dashboard/">
						{% endif %}
						{% if message %}
							<p class="errornote">
								{{message}}
							</p>
						{% endif %}

						<form class="login-form" action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}

							<div class="form-group mb-3">
								<div class="input-group mb-2">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="ni ni-circle-08"></i></span>
									</div>
									<input class="form-control" name="username" placeholder="Username" type="text">
								</div>
								<small class="text-danger text-left">{{ form.username.errors }}</small>
							</div>

							<div class="form-group mb-3">
								<div class="input-group mb-2">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
									</div>
									<input id="password-input" class="form-control" name="password" placeholder="Password" type="password">
									<a class="show-password fa fa-eye"></a>
									<input type="hidden" name="next" value="{{ next }}">
								</div>
								<small class="text-danger text-left">{{ form.password.errors }}</small>
							</div>
							
							<div class="text-center">
								<input class="login-btn my-4 pl-5 pr-5 text-capitalize" type="submit" value="{% trans 'Log in' %}">
							</div>
						</form>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

dashboard/templates/profile.html
{% extends 'dashboard.html' %}

{% load static %}
{% block style %} {{ block.super }}
<link type="text/css" href="{% static 'profile.css' %}" rel="stylesheet">
{% endblock style %}
{% block dashboardContent %}

<div class="row">
    <div class="col-6">
        <div class="dashboard-title">Profile</div>
        <small>Manage your profile</small>
    </div>
    <div class="col-6 edit-profile text-center mb-4 type="button" data-toggle="modal" data-target="#edit-profile-modal"">
        Edit Profile
    </div>
</div>
<hr class="mt-2">

<div class="container mt-5">
    <div class="row justify-content-center mb-5">
        <div class="col-12 text-center">  
            <form id="profile-form" action="{% url 'dashboard:profile_edit' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="profile-pic">
                    <div class="profile-pic shadow" style="background-image: url('{% if profile.avatar %}{{profile.avatar.url}}{% else %}{% static 'img/default-avatar.svg' %}{% endif %}')">
                        <i class="fa fa-camera change-pic" ></i>
                        <span>Change Image</span>
                    </div>
                </label>
                <input type="File" name="avatar" id="profile-pic">
            </form>
        </div>
        <div class="col-12 text-center">
            <p class="m-0 profile-name">{{profile.name_complete}}</p>
            <div class="row justify-content-center mt-2">
                <div class="col-lg-8">
                    <div class="profile-boi">
                        <p>{{profile.mini_about}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-6">
            <div class="col-lg-6 about-me">
                <p class="profile-title"><i class="ni ni-circle-08 mr-2"></i>About Me</p>
                <hr class="my-2">
                <p class="">{{profile.about}}</p>
            </div>
            <div class="col-lg-6 contact-me">
                <p class="profile-title"><i class="ni ni-chat-round mr-2"></i>Contact Me</p>
                <hr class="my-2">
                <a href="mailto:{{profile.email}}" class="social-media" target="_blank">
                    <div>
                        <i class="fas fa-envelope"></i>
                        {{profile.email}}
                    </div>
                </a>
                <a href="{{profile.phone}}" class="social-media" target="_blank">
                    <div>
                        <i class="fas fa-phone"></i>
                        {{profile.phone}}
                    </div>
                </a>
                <div class="text-center mt-3">
                    <a href="{{profile.github}}" class="social-media-inline" target="_blank">
                        <i class="fab fa-github"></i>
                    </a>
                    <a href="{{profile.linkedin}}" class="social-media-inline" target="_blank">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="{{profile.facebook}}" class="social-media-inline" target="_blank">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="{{profile.instagram}}" class="social-media-inline" target="_blank">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="{{profile.twitter}}" class="social-media-inline" target="_blank">
                        <i class="fab fa-twitter"></i>
                    </a>  
                </div>
            </div>

	</div>
    
</div>



<!-- Modal -->
<div class="modal fade" id="edit-profile-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content edit-profile-modal">
      <div class="modal-head">
        EDIT PROFILE
      </div>
      <div class="modal-body">


        <form class="edit-profile-form">
            <div class="row">
                <div class="col-md-12">
                    <div class="input-gr">
                    <i class="fas fa-user"></i>
                        <label class="label">Full Name</label>
                        <input type="text" id="full_name" class="form-control" value="{{profile.name_complete}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="input-gr">
                        <i class="fas fa-id-card"></i>
                        <label class="label" >Bio</label>
                        <textarea class="form-control" id="mini-about" rows="2"
                            placeholder="Write a short bio here ..." 
                        >{% if profile.mini_about %}{{profile.mini_about}}{% endif %}</textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="input-gr">
                        <i class="fas fa-address-card"></i>
                        <label class="label" >About Me</label>
                        <textarea class="form-control" id="about" rows="4" 
                        placeholder="Write a long bio here ..." 
                        >{% if profile.about %}{{profile.about}}{% endif %}</textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="input-gr">
                        <i class="fas fa-envelope"></i>
                        <label class="label">Email</label>
                        <input type="text" id="email" class="form-control" value="{% if profile.email %}{{profile.email}}{% endif %}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-gr">
                        <i class="fas fa-phone"></i>
                        <label class="label">Phone</label>
                        <input type="text" id="phone" class="form-control" value="{{profile.phone}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-gr">
                    <i class="fab fa-github"></i>
                        <label class="label">Github</label>
                        <input type="text" id="github" class="form-control" value="{{profile.github}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-gr">
                        <i class="fab fa-linkedin"></i>
                        <label class="label">LinkedIn</label>
                        <input type="text" id="linkedin" class="form-control" value="{{profile.linkedin}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-gr">
                        <i class="fab fa-facebook"></i>
                        <label class="label">Facebook</label>
                        <input type="text" id="facebook" class="form-control" value="{{profile.facebook}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-gr">
                        <i class="fab fa-twitter"></i>
                        <label class="label">Twitte</label>
                        <input type="text" id="twitter" class="form-control" value="{{profile.twitter}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-gr">
                        <i class="fab fa-instagram"></i>
                        <label class="label">Instagram</label>
                        <input type="text" id="instagram" class="form-control" value="{{profile.instagram}}">
                    </div>
                </div>
            </div>
        </form>
        <div id="form-errors"></div>

      </div>
      <div class="modal-footer">
        <a class="save" id="save-profile-edit">Save Changes</a>
        <a class="close" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>


<!-- profilechange success -->
<button style="display: none;" data-toggle="modal" data-target=".bd-example-modal-sm" id="change-success"></button>

<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content profile-change-success text-center">
        Your information has been changed successfully
        <i class="ni ni-check-bold"></i>
    </div>
  </div>
</div>
{% endblock dashboardContent %}